---
openapi: 1.0.0
info:
  title: Bauman Poker
  description: Онлайн-игра "Бомонский ПОКЕР"
  version: v1
servers:
  - url: http://[server ip]:80/
paths:
  /manage/health:
    get:
      tags:
      - Game-server API
      summary: Проверить доступность сервера
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v1/register:
    post:
      tags:
      - Game-server API
      summary: Зарегистрировать нового игрока
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
      responses:
        '200':
          description: Сессионные параметры
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AuthenticationResponse"
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  /api/v1/oauth/token:
    post:
      tags:
      - Game-server API
      summary: Аутентификация игрока
      description: Возможны два варианта аутентификации:
                    1) по имени пользователя и паролю (поля username и password заполняются; refresh-token = "")
                    2) по refresh-token (поля username и password = ""; в поле refresh-token записывается токен игрока)
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
      responses:
        '200':
          description: Сессионные параметры
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AuthenticationResponse"
        '401':
          description: Неверные имя пользователя или пароль, или refresh-token истек
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  /api/v1/oauth/revoke:
    delete:
      tags:
      - Game-server API
      summary: Завершение сессии игрока (в заголовке авторизации посылается refresh-token)
      security:
        - bearerAuth: [refresh-token]
      responses:
        '204':
          description: Успешное завершение сессии
          content:
            application/json:
              schema: {}
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  /api/v1/me:
    get:
      tags:
      - Game-server API
      summary: Получение информации о текущем игроке
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Информация об игроке
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserInfo"
        '401':
          description: access-token истек
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  /api/v1/rooms/matching:
    get:
      tags:
      - Game-server API
      summary: Поиск игровой комнаты
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Информация подобранной о комнате
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RoomInfo"
        '401':
          description: access-token истек
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  /api/v1/rooms/{roomUid}:
    get:
      tags:
      - Game-server API
      summary: Получение информации об игровой комнате по RoomUid
      security:
        - bearerAuth: [ ]
      parameters:
        - name: roomUid
          in: path
          description: UUID игровой комнаты
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Информация о комнате
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RoomInfo"
        '401':
          description: access-token истек
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '404':
          description: Комната не найдена
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  /api/v1/players/{userUid}:
    get:
      tags:
      - Game-server API
      summary: Получение информации об игроке по userUid
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userUid
          in: path
          description: UUID игрока
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Информация об игроке
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PlayerInfo"
        '401':
          description: access-token истек
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '404':
          description: Игрок не найден
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  /api/v1/rooms-ws/{roomUid}:
    get:
      tags:
      - Game-server API
      summary: WebSocket connection. Подключение к игровой комнате по RoomUid
      parameters:
        - name: roomUid
          in: path
          description: UUID игровой комнаты
          required: true
          schema:
            type: string
            format: uuid
        - name: uid
          in: query
          description: uid игрока, подключающегося к игровой комнате
          required: true
          schema:
            type: string
      responses:
        '101':
          description: Переход на протокол WebSocket. См. game-server-ws-api.yaml
          content:
            application/json:
              schema: {}
        '404':
          description: Комната не найдена
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"